"""add stripe payment columns to payments table

Revision ID: c9d60fa9eae1
Revises: 5992f0244e12
Create Date: 2025-10-26 16:24:19.723231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d60fa9eae1'
down_revision: Union[str, Sequence[str], None] = '5992f0244e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.add_column('payments', sa.Column('payment_intent_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_payments_payment_intent_id'), 'payments', ['payment_intent_id'], unique=False)
    op.create_index(op.f('ix_payments_session_id'), 'payments', ['session_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_session_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_intent_id'), table_name='payments')
    op.drop_column('payments', 'payment_intent_id')
    op.drop_column('payments', 'session_id')
    # ### end Alembic commands ###
